// form 1 initial values
export const initialVehicleValues = {
  brand: "",
  model: "",
  bodyType: "",
  fuelType: "",
  transmission: "",
  driveType: "",
  numberofGears: "",
  cylinders: "",
  doors: "",
  seats: "",
  enginePower: "",
  cubicCapacity: "",
  dateFirstRegistration: "",
  licenseCategory: "B",
  engineType: "",
  totalWeight: "",
  towingCapacity: "",
  loadCapacity: "",
  emptyWeight: "",
  vehicleFeature: {
    colour: "",
    interiorColour: "",
  },
  Condition: {
    vehicleCondition: "",
    lastInspectionAtMFK: "",
    abMFK: false,
    mileage: "",
    warranty: "",
  },
  price: { priceCHF: "", newPrice: "", priceOnRequest: false },
  technicalData: {
    width: "",
    height: "",
    length: "",
    typeApproval: "",
    vehicleIdetificationNumber: "",
    serialNumber: "",
  },
  detaildata: {
    directParallelImport: false,
    tyres: false,
    specialFutures: "",
  },
  extrafuture: {
    youtubeLink: "",
  },
};
